spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  session:
    jdbc:
      initialize-schema: always
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${OAUTH_CLIENT_ID}
            clientSecret: ${OAUTH_CLIENT_SECRET}
logging:
  file:
    name: logs/api.log
management:
  datadog:
    metrics:
      export:
        enabled: false